name: Python application

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
      - name: Black
        if: always()
        run: black --check ./
      - name: Pylint
        if: always()
        run: pylint app --fail-under=9.0
      - name: Pytest
        if: always()
        run: pytest
